### ISSUE TITLE
Bootloop after modding

### ISSUE THREAD

**Issue by leandrofriedrich** [berobloom/LSCIndoorCameraLocal1080p#2] opened 2024-04-07 17:12 UTC
Hi, i recently aquired one of these cameras and found this guide which i followed, however it seems to be bootlooping in some form after modding it. I get the "Starting LSC Camera" sound and the beep

https://pastebin.com/74F3ZEwY this is the full bootup log if it contains anything interesting.

Is there any chance i can get some help figuring out why it loops?
thanks in advance

**Comment by berobloom** [comment] 2024-04-07 18:20
Hey @leandrofriedrich,

It looks like the application has some problems reaching `product.cof`.

```
2024-04-07 18:04:52 [1712509492:957] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[CONST_PARAM] key[manual_ircut]
```

What is the contents of your `product.cof` on your sdcard?

**Comment by berobloom** [comment] 2024-05-08 06:04
Hello @leandrofriedrich, it has been over a month, I cannot reproduce this. Do you still have issues?

**Comment by berobloom** [comment] 2024-05-14 20:38
I am closing this Issue. Let me know if you run into problems again.

**Closed as not planned by berobloom** 2024-05-14 20:38 UTC
