### ISSUE TITLE
Bricked Device?

### ISSUE THREAD

**Issue by tobs1895** [berobloom/LSCIndoorCameraLocal1080p#1] opened 2024-02-18 15:06 UTC
Hello,
I followed this nice tutorial.
I came till step 11 without problems, but when I tried to write the flash
with new the file (fullmod.bin), I recognized it was too big.
It could not be flashed.
I think I missed something in the modifying process.
Due to, I already had done the erasing command, I decided to flash 
the original fulldump.bin file.
Then I did the reset.

Now I only get these two lines output on power on:

ROM:    Use nor flash.
ERR:    Flash is corrupted

Is that a U-Boot message or is U-Boot lost?
Do you know where U-Boot is stored?

Thanks a lot!

**Comment by berobloom** [comment] 2024-02-19 21:31
Hi Tobs thanks for reaching out.

I am not sure what happened that would result in this state. It should definitely not be bigger than the flash. That would result in a corrupt flash indeed.

I have followed my own instructions in this repo with multiple camera's and never had issues.

Maybe somewhere the tutorial you have missed something or maybe you have an older/newer model. The most important thing is that the camera has a Fullhan FH8626V100 Soc. You will find this specific model on the camera.

If you can give me the `fulldump.bin` and the `fullmod.bin` file I could check out what went wrong.

I see you have bricked your device. No worries. I made the same mistake before. You can still re-flash it using a ch341a programmer. https://www.amazon.com/KOOBOOK-CH341A-Programmer-Adapter-Converter/dp/B07VMPZFWH

If you still have issues I can modify your fulldump.bin and send it to you, or just give you my own modified dump.

Cheers!

**Comment by tobs1895** [comment] 2024-02-24 16:47
Hello Berobloom,
thank you for your help.
with the CH341A Programmer I could read the Data of another Camera and unbrick the first one .
It worked well! 
Maybe its related to a bad SDcard.
I tried a few things like formatting and writing zeros to SDcard, but the file I get with this card is completely diffrent to that
I grabbed with the programmer.
Sadly I do not have anther SDcard to have a try at the moment.

Have a nice day and thank you very much for that nice guide!

**Comment by berobloom** [comment] 2024-02-24 20:23
You are welcome. Contact me if you need any help.

**Comment by tobs1895** [comment] 2024-05-06 16:51
Hello Berobloom,
I need some help again.
It seems to me the cam is running, but I can not connect.
I tried with tinyCam and with the LSC-Prox. no luck.
Maybe it is a problem with the credentials.
I tried with default PSW and also generated new credentials with the same result.

Here is the console-output of dgoit. Maybe it helps.
```
# ./dgiot
ver: 7.6.32
info: timeout = 16
2024-05-06 16:37:59 [1715013479:083] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/etc/conf/product.cof] failed! section[CONST_PARAM] key[manual_ircut]

CThreadManager::CThreadManager()>>>>>>>>>
2024-05-06 16:37:59 [1715013479:093] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/etc/conf/product.cof] failed! section[CONST_PARAM] key[hardtype]

mount: mounting /dev/mmcblk0p1 on /mnt failed: Device or resource busy
2024-05-06 16:37:59 [1715013479:120] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[AGING_SETTING] key[aging_test]

2024-05-06 16:37:59 [1715013479:122] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[CONST_PARAM] key[manual_ircut]

2024-05-06 16:37:59 [1715013479:126] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[CONST_PARAM] key[lamp_board_value]

2024-05-06 16:37:59 [1715013479:132] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[CONST_PARAM] key[hardtype]

2024-05-06 16:37:59 [1715013479:135] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[DEFAULT_SETTING] key[language]

2024-05-06 16:37:59 [1715013479:137] DGIOT ../../tuya/Tuya_common.cpp 0302 read_profile_string(): parse ini file[/mnt/product.cof] failed! section[DEFAULT_SETTING] key[forceBurnLicense]

2024-05-06 16:37:59 [1715013479:141] DGIOT ../../tuya/Tuya_common.cpp 0426 write_profile_string(): Fail to open file ! 

2024-05-06 16:37:59 [1715013479:142] DGIOT ../../tuya/Tuya_common.cpp 0705 SetProductCof(): write ini ircut_flip error

cp: can't create '/etc/conf/product.cof-bk': Read-only file system
2024-05-06 16:37:59 [1715013479:212] DGIOT ../../Main.cpp 0940 checkDevLicense(): get from eeprom.

CryptoRead error
2024-05-06 16:38:00 [1715013480:276] DGIOT ../../Main.cpp 0989 checkDevLicense(): get from /etc/conf/deviceinfo.

[dsp] version: V2.0.0(gde7e157),build: 2020-09-09
[isp] version:  V2.0.0(gf71a525),build: 2020-09-09
[ispcore] version:      V2.0.0(gf71a525),build: 2020-09-09
ADV_ISP version:                V2.0.0(gce910e3), build: 2020-09-09
[sensor] version:       V2.0.0(gf71a525),build: 2020-09-09
pid1=0x20,pid2=0x6
mis2006_i2c_addr=0x60
probe sensor: mis2006_mipi
[mipi] version: V2.0.0(gf71a525),build: 2020-09-09
[sensor] version:       V2.0.0(gf71a525),build: 2020-09-09
pid1=0x20,pid2=0x6
mis2006_i2c_addr=0x60
[sensor] version:       V2.0.0(gf71a525),build: 2020-09-09
file_name is ./day_mis2006_mipi_attr.hex
isp param version is not compitable with current setting!
file_name is ./night_mis2006_mipi_attr.hex
Save night param hex success
pstCeCfg is 1--0--54--50
==================AudioCreate start==================
[ACW_MPI] version: V2.0.0(g3c2d587),build: 2020-09-09
CPacketManagerImp::CPacketManagerImp()>>>>>>>>>
sm_packetBuf null use self heap memory!
Adjust Page!
Packet usage : 0K / 1023K, 0%


========in AencAACStreamProc=========



========in AencG711uStreamProc=========

size = 512

----------------------[05-06 16:38:00]
printJsonValue
        ---zzb: ../../Net/NetConfigHook.cpp-Line60: =[{"Auth":"WPA2PSK","Channel":6,"Enable":false,"EncrypType":"CCMP","GateWay":"192.168.0.255","HostIP":"192.168.0.1","Keys":"12345678","Netmask":"255.255.255.0","SSID":"dgiot"}
]--
2024-05-06 16:38:02 [1715013482:986] DGIOT ../../Storage/StorageManager.cpp 0297 Init(): Disk Free Size : 62449844224

2024-05-06 16:38:02 [1715013482:988] DGIOT ../../Storage/DiskManager.cpp 0094 Init(): Disk ---> total : 62518624256, used : 68780032, free : 62449844224

2024-05-06 16:38:02 [1715013482:995] DGIOT ../../Net/NetConfigHook.cpp 0077 Init(): ======================================CNetConfigHook::Init()====================1==================

2024-05-06 16:38:02 [1715013482:998] DGIOT ../../Net/NetConfigHook.cpp 0087 Init(): ======================================CNetConfigHook::Init()====================2==================

===========>Middleware WifiStationModeCreate
ZTT24,regenbogenschaf
killall: udhcpd: no process killed
killall: hostapd: no process killed
cmd : wpa_supplicant -Dnl80211 -iwlan0 -c /tmp/wpa_supplicant.conf &
fread errno = 2
fread ret = 0
pipe :  Selected interface 'wlan0'
wpa_state=ASSOCIATING
ip_address=192.168.67.124
address=20:67:e0:67:50:dc

wpa_cli status ------>unknown...
2024-05-06 16:38:06 [1715013486:888] DGIOT ../../Net/NetConfigHook.cpp 0303 ThreadProc(): wifi is disconected...

fread errno = 2
fread ret = 0
pipe :  Selected interface 'wlan0'
bssid=98:0d:67:9e:d2:77
ssid=ZTT24
id=0
mode=station
pairwise_cipher=CCMP
group_cipher=CCMP
key_mgmt=WPA2-PSK
wpa_state=COMPLETED
ip_address=192.168.67.124
address=20:67:e0:67:50:dc

wifi connected...
udhcpc -b -i wlan0 -h dgiot -s /usr/share/udhcpc/default.script
ifconfig: ioctl 0x8913 failed: No such device
udhcpc: option -h NAME is deprecated, use -x hostname:NAME
udhcpc: started, v1.26.2
Setting IP address 0.0.0.0 on wlan0
udhcpc: sending discover
udhcpc: sending select for 192.168.67.124
udhcpc: lease of 192.168.67.124 obtained, lease time 172800
Setting IP address 192.168.67.124 on wlan0
Deleting routers
route: ioctl 0x890c failed: No such process
Adding router 192.168.67.222
Recreating /var/nm/resolv.conf
 Adding DNS server 192.168.67.222
ifconfig: ioctl 0x8913 failed: No such device
Threads:
               Name            PID  Prior State
_______________________________________________________
                    Main        219   64  Normal
                 FeedDog        220   50  Normal
            TimerManager        235   50  Normal
                  Pooled        236   50  Normal
          IndicaotrLight        237   50  Normal
            AudioManager        245   50  Normal
             AudioPrompt        246   50  Normal
            NetInterFace        251   50  Normal
                  Pooled        259   50  Normal
            CDiskManager        250   50  Normal
         CStorageManager        249   50  Normal
_________________________________________
          NoName 9450 Idel
    EventManager 10000 Idel
Cap(CaptureGetChannels , 1841):===========>Middleware CaptureGetChannels
Cap(CaptureCreate , 1905):===========>Middleware CaptureCreate ch 0
channel_max is 1
!!!FH_BGM_InitMem ok
!!!FH_BGM_SetConfig ok
!!!FH_BGM_Enable ok
bind ok!
CCaptureManager::start(0)(1)......
sched set 98, 2
Cap(CaptureSetOSDSwitch , 2212):===========>CaptureSetOSDSwitch
Cap(isp param version is not compitable with current setting!
CaptureSetFormat , 2255):===========>Middleware CaptureSetFormat
Cap(CaptureSetFormat , 2255):===========>Middleware CaptureSetFormat
CCaptureManager::start(1)(1)......
Cap(CaptureStart , 2269):===========> start Middleware CaptureStart,channel=0,dwType=0
Cap(CaptureStart , 2269):===========> start Middleware CaptureStart,channel=0,dwType=1
Binding main socket 15
Listening on main socket 15
ADV_SMARTIR version:            V2.0.0(gce910e3), build: 2020-09-09
*********900---640
2024-05-06 16:38:15 [1715013495:544] DGIOT ../../Produce/Tutk.cpp 0890 thread_Login(): IOTC_Device_Login() error ret = -60

2024-05-06 16:38:34 [1715013514:962] DGIOT ../../Produce/Tutk.cpp 1680 thread_ForAVServerStart(): avServStart3 failed SID[0] code[-20015]!!!

2024-05-06 16:38:39 [1715013519:737] DGIOT ../../Produce/Tutk.cpp 1680 thread_ForAVServerStart(): avServStart3 failed SID[0] code[-20015]!!!

2024-05-06 16:38:42 [1715013522:298] DGIOT ../../Produce/Tutk.cpp 1680 thread_ForAVServerStart(): avServStart3 failed SID[0] code[-20015]!!!

2024-05-06 16:38:43 [1715013523:391] DGIOT ../../Produce/Tutk.cpp 1680 thread_ForAVServerStart(): avServStart3 failed SID[0] code[-20015]!!!

2024-05-06 16:38:50 [1715013530:880] DGIOT ../../Produce/Tutk.cpp 0890 thread_Login(): IOTC_Device_Login() error ret = -60




```

**Comment by berobloom** [comment] 2024-05-08 06:01
Hello @tobs1895 ,

I miss some output of the init script that is run before the execution of ./dgiot. Are you sure you followed everything in the instructions?

**Comment by berobloom** [comment] 2024-06-22 11:46
It has been a month. I cannot reproduce this. Let me know if you need further help. I will close this issue.

**Closed as not planned by berobloom** 2024-06-22 11:46 UTC
